services:
  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    image: afriauth_web_image
    container_name: afriauth_web_container
    volumes:
      - .:/app:z
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: /entrypoint
    networks:
      - afriauth_docker_network

networks:
  afriauth_docker_network:
    external: true

volumes:
  logs_store: {}
