on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Deploy backend-end service

jobs:
  deploy:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.
