on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

name: Deploy backend-end service

jobs:
  deploy:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Docker Build & Push Django Backend to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "./docker/local/django/Dockerfile"
          IMAGE_NAME: "afripoint/afriauth_backend"
          LATEST: "true"

      - name: Docker Build & Push Client to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "./client/docker/Dockerfile"
          IMAGE_NAME: "afripoint/afriauth_client"
          LATEST: "true"


      # - name: Docker Build & Push to Docker Hub
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKERFILE: "./docker/local/postgres/Dockerfile"
      #     IMAGE_NAME: "afripoint/afriauth_postgres"
      #     LATEST: "true"

      # - name: Celery Worker Build & Push to Docker Hub
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKERFILE: "./docker/local/django/Dockerfile"
      #     IMAGE_NAME: "afripoint/afriauth_celeryworker"
      #     LATEST: "true"

      # - name: Celery Beat Build & Push to Docker Hub
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     DOCKERFILE: "./docker/local/django/Dockerfile"
      #     IMAGE_NAME: "afripoint/afriauth_celerybeat"
      #     LATEST: "true"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_TEST_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/server_config
            git checkout testing
            git reset --hard HEAD
            git pull origin testing
            docker stack deploy -c /root/server_configuration/docker-compose.yml afripointauth 

          
